# Generated by Django 2.0.5 on 2018-06-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='cleared',
            field=models.BooleanField(help_text=' .cleared with the bank?'),
        ),
        migrations.AlterField(
            model_name='check',
            name='type',
            field=models.CharField(choices=[('CR', 'credit'), ('DR', 'debit'), ('SV', 'savings'), ('DT', 'debt reduction')], help_text=' .credit or debit', max_length=2),
        ),
    ]
